### ISSUE TITLE
Add license for ArazGraph

### ISSUE THREAD

**Issue by m-rest** [arabed/ArazGraph#1]
Hi Ara, could you consider adding a license to the class? I am currently turning this class into a JUCE module at https://github.com/m-rest/ArazGraph and would like to add a proper license to it.

Thanks!

**Comment by arabed** [comment]
Will do! Let me know if you need further help...Many thanks!Ara

**Comment by arabed** [comment]
Please check it out! I add a new license file and also add the license notice to ArazGraph.xxx files.
Cheers!

**Comment by m-rest** [comment]
Thanks, will merge accordingly!
